/**
 * Meme template catalog - All templates from memegen.link
 * Auto-generated from memegen.link API
 */

export interface MemeTemplate {
  id: string;
  name: string;
  description: string;
  example: string;
  slots: number;
}

export const templates: Record<string, MemeTemplate> = {
  'aag': {
    id: 'aag',
    name: 'Ancient Aliens Guy',
    description: 'Ancient Aliens Guy meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'ackbar': {
    id: 'ackbar',
    name: 'It\'s A Trap!',
    description: 'It\'s A Trap! meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'afraid': {
    id: 'afraid',
    name: 'Afraid to Ask Andy',
    description: 'Afraid to Ask Andy meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'agnes': {
    id: 'agnes',
    name: 'Agnes Harkness Winking',
    description: 'Agnes Harkness Winking meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'aint-got-time': {
    id: 'aint-got-time',
    name: 'Sweet Brown',
    description: 'Sweet Brown meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'ams': {
    id: 'ams',
    name: 'Awkward Moment Seal',
    description: 'Awkward Moment Seal meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'ants': {
    id: 'ants',
    name: 'Do You Want Ants?',
    description: 'Do You Want Ants? meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'apcr': {
    id: 'apcr',
    name: 'Almost Politically Correct Redneck',
    description: 'Almost Politically Correct Redneck meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'astronaut': {
    id: 'astronaut',
    name: 'Always Has Been',
    description: 'Always Has Been meme template',
    example: 'Custom text',
    slots: 4,
  },
  'atis': {
    id: 'atis',
    name: 'And Then I Said',
    description: 'And Then I Said meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'away': {
    id: 'away',
    name: 'Life... Finds a Way',
    description: 'Life... Finds a Way meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'awesome': {
    id: 'awesome',
    name: 'Socially Awesome Penguin',
    description: 'Socially Awesome Penguin meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'awesome-awkward': {
    id: 'awesome-awkward',
    name: 'Socially Awesome Awkward Penguin',
    description: 'Socially Awesome Awkward Penguin meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'awkward': {
    id: 'awkward',
    name: 'Socially Awkward Penguin',
    description: 'Socially Awkward Penguin meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'awkward-awesome': {
    id: 'awkward-awesome',
    name: 'Socially Awkward Awesome Penguin',
    description: 'Socially Awkward Awesome Penguin meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'bad': {
    id: 'bad',
    name: 'You Should Feel Bad',
    description: 'You Should Feel Bad meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'badchoice': {
    id: 'badchoice',
    name: 'Milk Was a Bad Choice',
    description: 'Milk Was a Bad Choice meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'balloon': {
    id: 'balloon',
    name: 'Running Away Balloon',
    description: 'Running Away Balloon meme template',
    example: 'Custom text',
    slots: 3,
  },
  'bd': {
    id: 'bd',
    name: 'Butthurt Dweller',
    description: 'Butthurt Dweller meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'because': {
    id: 'because',
    name: 'Men in Black',
    description: 'Men in Black meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'bender': {
    id: 'bender',
    name: 'I\'m Going to Build My Own Theme Park',
    description: 'I\'m Going to Build My Own Theme Park meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'bihw': {
    id: 'bihw',
    name: 'But It\'s Honest Work',
    description: 'But It\'s Honest Work meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'bilbo': {
    id: 'bilbo',
    name: 'Why Shouldn\'t I Keep It',
    description: 'Why Shouldn\'t I Keep It meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'biw': {
    id: 'biw',
    name: 'Baby Insanity Wolf',
    description: 'Baby Insanity Wolf meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'blb': {
    id: 'blb',
    name: 'Bad Luck Brian',
    description: 'Bad Luck Brian meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'boat': {
    id: 'boat',
    name: 'I Should Buy a Boat Cat',
    description: 'I Should Buy a Boat Cat meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'bongo': {
    id: 'bongo',
    name: 'Bongo Cat',
    description: 'Bongo Cat meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'both': {
    id: 'both',
    name: 'Why Not Both?',
    description: 'Why Not Both? meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'box': {
    id: 'box',
    name: 'What\'s in the box!?',
    description: 'What\'s in the box!? meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'bs': {
    id: 'bs',
    name: 'This is Bull, Shark',
    description: 'This is Bull, Shark meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'bus': {
    id: 'bus',
    name: 'Two Guys on a Bus',
    description: 'Two Guys on a Bus meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'buzz': {
    id: 'buzz',
    name: 'X, X Everywhere',
    description: 'X, X Everywhere meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'cake': {
    id: 'cake',
    name: 'Office Space Milton',
    description: 'Office Space Milton meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'captain': {
    id: 'captain',
    name: 'I am the Captain Now',
    description: 'I am the Captain Now meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'captain-america': {
    id: 'captain-america',
    name: 'Captain America Elevator Fight Dad Joke',
    description: 'Captain America Elevator Fight Dad Joke meme template',
    example: 'Custom text',
    slots: 3,
  },
  'cb': {
    id: 'cb',
    name: 'Confession Bear',
    description: 'Confession Bear meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'cbb': {
    id: 'cbb',
    name: 'Communist Bugs Bunny',
    description: 'Communist Bugs Bunny meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'cbg': {
    id: 'cbg',
    name: 'Comic Book Guy',
    description: 'Comic Book Guy meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'center': {
    id: 'center',
    name: 'What is this, a Center for Ants?!',
    description: 'What is this, a Center for Ants?! meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'ch': {
    id: 'ch',
    name: 'Captain Hindsight',
    description: 'Captain Hindsight meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'chair': {
    id: 'chair',
    name: 'American Chopper Argument',
    description: 'American Chopper Argument meme template',
    example: 'Custom text',
    slots: 6,
  },
  'cheems': {
    id: 'cheems',
    name: 'Cheems',
    description: 'Cheems meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'chosen': {
    id: 'chosen',
    name: 'You Were the Chosen One!',
    description: 'You Were the Chosen One! meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'cmm': {
    id: 'cmm',
    name: 'Change My Mind',
    description: 'Change My Mind meme template',
    example: 'Custom text',
    slots: 1,
  },
  'country': {
    id: 'country',
    name: 'What a Country',
    description: 'What a Country meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'crazypills': {
    id: 'crazypills',
    name: 'I Feel Like I\'m Taking Crazy Pills',
    description: 'I Feel Like I\'m Taking Crazy Pills meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'crow': {
    id: 'crow',
    name: 'Get Better Material',
    description: 'Get Better Material meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'cryingfloor': {
    id: 'cryingfloor',
    name: 'Crying on Floor',
    description: 'Crying on Floor meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'db': {
    id: 'db',
    name: 'Distracted Boyfriend',
    description: 'Distracted Boyfriend meme template',
    example: 'Custom text',
    slots: 3,
  },
  'dbg': {
    id: 'dbg',
    name: 'Expectation vs. Reality',
    description: 'Expectation vs. Reality meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'dg': {
    id: 'dg',
    name: 'Distracted Girlfriend',
    description: 'Distracted Girlfriend meme template',
    example: 'Custom text',
    slots: 3,
  },
  'disastergirl': {
    id: 'disastergirl',
    name: 'Disaster Girl',
    description: 'Disaster Girl meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'dodgson': {
    id: 'dodgson',
    name: 'See? Nobody Cares',
    description: 'See? Nobody Cares meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'doge': {
    id: 'doge',
    name: 'Doge',
    description: 'Doge meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'dragon': {
    id: 'dragon',
    name: 'What Color Do You Want Your Dragon',
    description: 'What Color Do You Want Your Dragon meme template',
    example: 'Custom text',
    slots: 1,
  },
  'drake': {
    id: 'drake',
    name: 'Drakeposting',
    description: 'Drakeposting meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'drowning': {
    id: 'drowning',
    name: 'Drowning High Five',
    description: 'Drowning High Five meme template',
    example: 'Custom text',
    slots: 3,
  },
  'drunk': {
    id: 'drunk',
    name: 'Drunk Baby',
    description: 'Drunk Baby meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'ds': {
    id: 'ds',
    name: 'Daily Struggle',
    description: 'Daily Struggle meme template',
    example: 'Custom text',
    slots: 3,
  },
  'dsm': {
    id: 'dsm',
    name: 'Dating Site Murderer',
    description: 'Dating Site Murderer meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'dwight': {
    id: 'dwight',
    name: 'Schrute Facts',
    description: 'Schrute Facts meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'elf': {
    id: 'elf',
    name: 'You Sit on a Throne of Lies',
    description: 'You Sit on a Throne of Lies meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'elmo': {
    id: 'elmo',
    name: 'Elmo Choosing Cocaine',
    description: 'Elmo Choosing Cocaine meme template',
    example: 'Custom text',
    slots: 5,
  },
  'ermg': {
    id: 'ermg',
    name: 'Ermahgerd',
    description: 'Ermahgerd meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'exit': {
    id: 'exit',
    name: 'Left Exit 12 Off Ramp',
    description: 'Left Exit 12 Off Ramp meme template',
    example: 'Custom text',
    slots: 3,
  },
  'fa': {
    id: 'fa',
    name: 'Forever Alone',
    description: 'Forever Alone meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'facepalm': {
    id: 'facepalm',
    name: 'Facepalm',
    description: 'Facepalm meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'fbf': {
    id: 'fbf',
    name: 'Foul Bachelor Frog',
    description: 'Foul Bachelor Frog meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'feelsgood': {
    id: 'feelsgood',
    name: 'Feels Good',
    description: 'Feels Good meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'fetch': {
    id: 'fetch',
    name: 'Stop Trying to Make Fetch Happen',
    description: 'Stop Trying to Make Fetch Happen meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'fine': {
    id: 'fine',
    name: 'This is Fine',
    description: 'This is Fine meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'firsttry': {
    id: 'firsttry',
    name: 'First Try!',
    description: 'First Try! meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'fmr': {
    id: 'fmr',
    name: 'Fuck Me, Right?',
    description: 'Fuck Me, Right? meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'friends': {
    id: 'friends',
    name: 'Are You Two Friends?',
    description: 'Are You Two Friends? meme template',
    example: 'Custom text',
    slots: 3,
  },
  'fry': {
    id: 'fry',
    name: 'Futurama Fry',
    description: 'Futurama Fry meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'fwp': {
    id: 'fwp',
    name: 'First World Problems',
    description: 'First World Problems meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'gandalf': {
    id: 'gandalf',
    name: 'Confused Gandalf',
    description: 'Confused Gandalf meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'gb': {
    id: 'gb',
    name: 'Galaxy Brain',
    description: 'Galaxy Brain meme template',
    example: 'Custom text',
    slots: 4,
  },
  'gears': {
    id: 'gears',
    name: 'You Know What Really Grinds My Gears?',
    description: 'You Know What Really Grinds My Gears? meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'genie': {
    id: 'genie',
    name: 'Genie Lamp',
    description: 'Genie Lamp meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'ggg': {
    id: 'ggg',
    name: 'Good Guy Greg',
    description: 'Good Guy Greg meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'glasses': {
    id: 'glasses',
    name: 'Peter Parker\'s Glasses',
    description: 'Peter Parker\'s Glasses meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'gone': {
    id: 'gone',
    name: 'And It\'s Gone',
    description: 'And It\'s Gone meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'grave': {
    id: 'grave',
    name: 'Grant Gustin Next To Oliver Queen\'s Grave',
    description: 'Grant Gustin Next To Oliver Queen\'s Grave meme template',
    example: 'Custom text',
    slots: 3,
  },
  'gru': {
    id: 'gru',
    name: 'Gru\'s Plan',
    description: 'Gru\'s Plan meme template',
    example: 'Custom text',
    slots: 4,
  },
  'grumpycat': {
    id: 'grumpycat',
    name: 'Grumpy Cat',
    description: 'Grumpy Cat meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'hagrid': {
    id: 'hagrid',
    name: 'I Should Not Have Said That',
    description: 'I Should Not Have Said That meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'handshake': {
    id: 'handshake',
    name: 'Epic Handshake',
    description: 'Epic Handshake meme template',
    example: 'Custom text',
    slots: 3,
  },
  'happening': {
    id: 'happening',
    name: 'It\'s Happening',
    description: 'It\'s Happening meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'harold': {
    id: 'harold',
    name: 'Hide the Pain Harold',
    description: 'Hide the Pain Harold meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'headaches': {
    id: 'headaches',
    name: 'Types of Headaches',
    description: 'Types of Headaches meme template',
    example: 'Custom text',
    slots: 1,
  },
  'hipster': {
    id: 'hipster',
    name: 'Hipster Barista',
    description: 'Hipster Barista meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'home': {
    id: 'home',
    name: 'We Have Food at Home',
    description: 'We Have Food at Home meme template',
    example: 'Custom text',
    slots: 3,
  },
  'icanhas': {
    id: 'icanhas',
    name: 'I Can Has Cheezburger?',
    description: 'I Can Has Cheezburger? meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'imsorry': {
    id: 'imsorry',
    name: 'Oh, I\'m Sorry, I Thought This Was America',
    description: 'Oh, I\'m Sorry, I Thought This Was America meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'inigo': {
    id: 'inigo',
    name: 'Inigo Montoya',
    description: 'Inigo Montoya meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'interesting': {
    id: 'interesting',
    name: 'The Most Interesting Man in the World',
    description: 'The Most Interesting Man in the World meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'ive': {
    id: 'ive',
    name: 'Jony Ive Redesigns Things',
    description: 'Jony Ive Redesigns Things meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'iw': {
    id: 'iw',
    name: 'Insanity Wolf',
    description: 'Insanity Wolf meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'jd': {
    id: 'jd',
    name: 'Joseph Ducreux',
    description: 'Joseph Ducreux meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'jetpack': {
    id: 'jetpack',
    name: 'Nothing To Do Here',
    description: 'Nothing To Do Here meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'jim': {
    id: 'jim',
    name: 'Jim Halpert Pointing to Whiteboard',
    description: 'Jim Halpert Pointing to Whiteboard meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'joker': {
    id: 'joker',
    name: 'It\'s Simple, Kill the Batman',
    description: 'It\'s Simple, Kill the Batman meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'jw': {
    id: 'jw',
    name: 'Probably Not a Good Idea',
    description: 'Probably Not a Good Idea meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'keanu': {
    id: 'keanu',
    name: 'Conspiracy Keanu',
    description: 'Conspiracy Keanu meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'kermit': {
    id: 'kermit',
    name: 'But That\'s None of My Business',
    description: 'But That\'s None of My Business meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'khaby-lame': {
    id: 'khaby-lame',
    name: 'Khaby Lame Shrug',
    description: 'Khaby Lame Shrug meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'kk': {
    id: 'kk',
    name: 'Karate Kyle',
    description: 'Karate Kyle meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'kombucha': {
    id: 'kombucha',
    name: 'Kombucha Girl',
    description: 'Kombucha Girl meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'kramer': {
    id: 'kramer',
    name: 'Kramer, What\'s Going On In There?',
    description: 'Kramer, What\'s Going On In There? meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'leo': {
    id: 'leo',
    name: 'Leo Strutting',
    description: 'Leo Strutting meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'light': {
    id: 'light',
    name: 'Everything the Light Touches is Our Kingdom',
    description: 'Everything the Light Touches is Our Kingdom meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'live': {
    id: 'live',
    name: 'Do It Live!',
    description: 'Do It Live! meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'll': {
    id: 'll',
    name: 'Laughing Lizard',
    description: 'Laughing Lizard meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'lrv': {
    id: 'lrv',
    name: 'Laundry Room Viking',
    description: 'Laundry Room Viking meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'made': {
    id: 'made',
    name: 'I Made This',
    description: 'I Made This meme template',
    example: 'Custom text',
    slots: 5,
  },
  'mb': {
    id: 'mb',
    name: 'Member Berries',
    description: 'Member Berries meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'michael-scott': {
    id: 'michael-scott',
    name: 'Michael Scott No God No',
    description: 'Michael Scott No God No meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'midwit': {
    id: 'midwit',
    name: 'Midwit',
    description: 'Midwit meme template',
    example: 'Custom text',
    slots: 3,
  },
  'millers': {
    id: 'millers',
    name: 'You Guys Are Getting Paid?',
    description: 'You Guys Are Getting Paid? meme template',
    example: 'Custom text',
    slots: 4,
  },
  'mini-keanu': {
    id: 'mini-keanu',
    name: 'Mini Keanu Reeves',
    description: 'Mini Keanu Reeves meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'mmm': {
    id: 'mmm',
    name: 'Minor Mistake Marvin',
    description: 'Minor Mistake Marvin meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'money': {
    id: 'money',
    name: 'Shut Up and Take My Money!',
    description: 'Shut Up and Take My Money! meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'mordor': {
    id: 'mordor',
    name: 'One Does Not Simply Walk into Mordor',
    description: 'One Does Not Simply Walk into Mordor meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'morpheus': {
    id: 'morpheus',
    name: 'Matrix Morpheus',
    description: 'Matrix Morpheus meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'mouth': {
    id: 'mouth',
    name: 'Woman Holding Dog\'s Mouth',
    description: 'Woman Holding Dog\'s Mouth meme template',
    example: 'Custom text',
    slots: 3,
  },
  'mw': {
    id: 'mw',
    name: 'I Guarantee It',
    description: 'I Guarantee It meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'nails': {
    id: 'nails',
    name: 'Guy Hammering Nails Into Sand',
    description: 'Guy Hammering Nails Into Sand meme template',
    example: 'Custom text',
    slots: 3,
  },
  'nice': {
    id: 'nice',
    name: 'So I Got That Goin\' For Me, Which is Nice',
    description: 'So I Got That Goin\' For Me, Which is Nice meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'noah': {
    id: 'noah',
    name: 'What the Hell is This?',
    description: 'What the Hell is This? meme template',
    example: 'Custom text',
    slots: 4,
  },
  'noidea': {
    id: 'noidea',
    name: 'I Have No Idea What I\'m Doing',
    description: 'I Have No Idea What I\'m Doing meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'ntot': {
    id: 'ntot',
    name: 'No Take, Only Throw',
    description: 'No Take, Only Throw meme template',
    example: 'Custom text',
    slots: 3,
  },
  'oag': {
    id: 'oag',
    name: 'Overly Attached Girlfriend',
    description: 'Overly Attached Girlfriend meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'officespace': {
    id: 'officespace',
    name: 'That Would Be Great',
    description: 'That Would Be Great meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'older': {
    id: 'older',
    name: 'An Older Code Sir, But It Checks Out',
    description: 'An Older Code Sir, But It Checks Out meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'oprah': {
    id: 'oprah',
    name: 'Oprah You Get a Car',
    description: 'Oprah You Get a Car meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'panik-kalm-panik': {
    id: 'panik-kalm-panik',
    name: 'Panik Kalm Panik',
    description: 'Panik Kalm Panik meme template',
    example: 'Custom text',
    slots: 3,
  },
  'patrick': {
    id: 'patrick',
    name: 'Push it somewhere else Patrick',
    description: 'Push it somewhere else Patrick meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'perfection': {
    id: 'perfection',
    name: 'Perfection',
    description: 'Perfection meme template',
    example: 'Custom text',
    slots: 6,
  },
  'persian': {
    id: 'persian',
    name: 'Persian Cat Room Guardian',
    description: 'Persian Cat Room Guardian meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'philosoraptor': {
    id: 'philosoraptor',
    name: 'Philosoraptor',
    description: 'Philosoraptor meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'pigeon': {
    id: 'pigeon',
    name: 'Is This a Pigeon?',
    description: 'Is This a Pigeon? meme template',
    example: 'Custom text',
    slots: 3,
  },
  'pooh': {
    id: 'pooh',
    name: 'Tuxedo Winnie the Pooh',
    description: 'Tuxedo Winnie the Pooh meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'pool': {
    id: 'pool',
    name: 'Mother Ignoring Kid Drowning In A Pool',
    description: 'Mother Ignoring Kid Drowning In A Pool meme template',
    example: 'Custom text',
    slots: 3,
  },
  'prop3': {
    id: 'prop3',
    name: 'Too Confusing, Too Extreme',
    description: 'Too Confusing, Too Extreme meme template',
    example: 'Custom text',
    slots: 1,
  },
  'ptj': {
    id: 'ptj',
    name: 'Phoebe Teaching Joey',
    description: 'Phoebe Teaching Joey meme template',
    example: 'Custom text',
    slots: 8,
  },
  'puffin': {
    id: 'puffin',
    name: 'Unpopular opinion puffin',
    description: 'Unpopular opinion puffin meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'red': {
    id: 'red',
    name: 'Oh, Is That What We\'re Going to Do Today?',
    description: 'Oh, Is That What We\'re Going to Do Today? meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'regret': {
    id: 'regret',
    name: 'I Immediately Regret This Decision!',
    description: 'I Immediately Regret This Decision! meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'remembers': {
    id: 'remembers',
    name: 'Pepperidge Farm Remembers',
    description: 'Pepperidge Farm Remembers meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'reveal': {
    id: 'reveal',
    name: 'Scooby Doo Reveal',
    description: 'Scooby Doo Reveal meme template',
    example: 'Custom text',
    slots: 4,
  },
  'right': {
    id: 'right',
    name: 'Anakin and Padme Change the World For the Better',
    description: 'Anakin and Padme Change the World For the Better meme template',
    example: 'Custom text',
    slots: 5,
  },
  'rollsafe': {
    id: 'rollsafe',
    name: 'Roll Safe',
    description: 'Roll Safe meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sad-biden': {
    id: 'sad-biden',
    name: 'Sad Joe Biden',
    description: 'Sad Joe Biden meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sad-boehner': {
    id: 'sad-boehner',
    name: 'Sad John Boehner',
    description: 'Sad John Boehner meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sad-bush': {
    id: 'sad-bush',
    name: 'Sad George Bush',
    description: 'Sad George Bush meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sad-clinton': {
    id: 'sad-clinton',
    name: 'Sad Bill Clinton',
    description: 'Sad Bill Clinton meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sad-obama': {
    id: 'sad-obama',
    name: 'Sad Barack Obama',
    description: 'Sad Barack Obama meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sadfrog': {
    id: 'sadfrog',
    name: 'Feels Bad Man',
    description: 'Feels Bad Man meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'saltbae': {
    id: 'saltbae',
    name: 'Salt Bae',
    description: 'Salt Bae meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'same': {
    id: 'same',
    name: 'They\'re The Same Picture',
    description: 'They\'re The Same Picture meme template',
    example: 'Custom text',
    slots: 3,
  },
  'sarcasticbear': {
    id: 'sarcasticbear',
    name: 'Sarcastic Bear',
    description: 'Sarcastic Bear meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'say': {
    id: 'say',
    name: 'Say the Line, Bart!',
    description: 'Say the Line, Bart! meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sb': {
    id: 'sb',
    name: 'Scumbag Brain',
    description: 'Scumbag Brain meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'scc': {
    id: 'scc',
    name: 'Sudden Clarity Clarence',
    description: 'Sudden Clarity Clarence meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'seagull': {
    id: 'seagull',
    name: 'Inhaling Seagull',
    description: 'Inhaling Seagull meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sf': {
    id: 'sf',
    name: 'Sealed Fate',
    description: 'Sealed Fate meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sk': {
    id: 'sk',
    name: 'Skeptical Third World Kid',
    description: 'Skeptical Third World Kid meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'ski': {
    id: 'ski',
    name: 'Super Cool Ski Instructor',
    description: 'Super Cool Ski Instructor meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'slap': {
    id: 'slap',
    name: 'Will Smith Slapping Chris Rock',
    description: 'Will Smith Slapping Chris Rock meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'snek': {
    id: 'snek',
    name: 'Skeptical Snake',
    description: 'Skeptical Snake meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'soa': {
    id: 'soa',
    name: 'Seal of Approval',
    description: 'Seal of Approval meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sohappy': {
    id: 'sohappy',
    name: 'I Would Be So Happy',
    description: 'I Would Be So Happy meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sohot': {
    id: 'sohot',
    name: 'So Hot Right Now',
    description: 'So Hot Right Now meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'soup-nazi': {
    id: 'soup-nazi',
    name: 'No Soup for You',
    description: 'No Soup for You meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'sparta': {
    id: 'sparta',
    name: 'This is Sparta!',
    description: 'This is Sparta! meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'spiderman': {
    id: 'spiderman',
    name: 'Spider-Man Pointing at Spider-Man',
    description: 'Spider-Man Pointing at Spider-Man meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'spirit': {
    id: 'spirit',
    name: 'Fake Spirit Halloween Costume',
    description: 'Fake Spirit Halloween Costume meme template',
    example: 'Custom text',
    slots: 5,
  },
  'spongebob': {
    id: 'spongebob',
    name: 'Mocking Spongebob',
    description: 'Mocking Spongebob meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'ss': {
    id: 'ss',
    name: 'Scumbag Steve',
    description: 'Scumbag Steve meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'stew': {
    id: 'stew',
    name: 'Baby, You\'ve Got a Stew Going',
    description: 'Baby, You\'ve Got a Stew Going meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'stonks': {
    id: 'stonks',
    name: 'Stonks',
    description: 'Stonks meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'stop': {
    id: 'stop',
    name: 'Stop It Patrick You\'re Scaring Him',
    description: 'Stop It Patrick You\'re Scaring Him meme template',
    example: 'Custom text',
    slots: 6,
  },
  'stop-it': {
    id: 'stop-it',
    name: 'Stop It, Get Some Help',
    description: 'Stop It, Get Some Help meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'success': {
    id: 'success',
    name: 'Success Kid',
    description: 'Success Kid meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'tenguy': {
    id: 'tenguy',
    name: '10 Guy',
    description: '10 Guy meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'toohigh': {
    id: 'toohigh',
    name: 'The Rent Is Too Damn High',
    description: 'The Rent Is Too Damn High meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'touch': {
    id: 'touch',
    name: 'Principal Skinner',
    description: 'Principal Skinner meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'tried': {
    id: 'tried',
    name: 'At Least You Tried',
    description: 'At Least You Tried meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'trump': {
    id: 'trump',
    name: 'Donald Trump',
    description: 'Donald Trump meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'ugandanknuck': {
    id: 'ugandanknuck',
    name: 'Ugandan Knuckles',
    description: 'Ugandan Knuckles meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'vince': {
    id: 'vince',
    name: 'Vince McMahon Reaction',
    description: 'Vince McMahon Reaction meme template',
    example: 'Custom text',
    slots: 3,
  },
  'wallet': {
    id: 'wallet',
    name: 'Patrick Star\'s Wallet',
    description: 'Patrick Star\'s Wallet meme template',
    example: 'Custom text',
    slots: 8,
  },
  'waygd': {
    id: 'waygd',
    name: 'What Are Ya Gonna Do?',
    description: 'What Are Ya Gonna Do? meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'wddth': {
    id: 'wddth',
    name: 'We Don\'t Do That Here',
    description: 'We Don\'t Do That Here meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'whatyear': {
    id: 'whatyear',
    name: 'What Year Is It?',
    description: 'What Year Is It? meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'winter': {
    id: 'winter',
    name: 'Winter is coming',
    description: 'Winter is coming meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'wishes': {
    id: 'wishes',
    name: 'Genie Rules',
    description: 'Genie Rules meme template',
    example: 'Custom text',
    slots: 1,
  },
  'wkh': {
    id: 'wkh',
    name: 'Who Killed Hannibal?',
    description: 'Who Killed Hannibal? meme template',
    example: 'Custom text',
    slots: 3,
  },
  'woman-cat': {
    id: 'woman-cat',
    name: 'Woman Yelling at a Cat',
    description: 'Woman Yelling at a Cat meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'wonka': {
    id: 'wonka',
    name: 'Condescending Wonka',
    description: 'Condescending Wonka meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'worst': {
    id: 'worst',
    name: 'The Worst Day Of Your Life So Far',
    description: 'The Worst Day Of Your Life So Far meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'xy': {
    id: 'xy',
    name: 'X all the Y',
    description: 'X all the Y meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'yallgot': {
    id: 'yallgot',
    name: 'Y\'all Got Any More of Them',
    description: 'Y\'all Got Any More of Them meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'yodawg': {
    id: 'yodawg',
    name: 'Xzibit Yo Dawg',
    description: 'Xzibit Yo Dawg meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'yuno': {
    id: 'yuno',
    name: 'Y U NO Guy',
    description: 'Y U NO Guy meme template',
    example: 'Top: "First line" / Bottom: "Second line"',
    slots: 2,
  },
  'zero-wing': {
    id: 'zero-wing',
    name: 'All Your Base Are Belong to Us',
    description: 'All Your Base Are Belong to Us meme template',
    example: 'Custom text',
    slots: 1,
  },
};

/**
 * Get template by ID
 */
export function getTemplate(id: string): MemeTemplate | undefined {
  return templates[id];
}

/**
 * Get all template IDs
 */
export function getTemplateIds(): string[] {
  return Object.keys(templates);
}

/**
 * Validate if a template ID exists
 */
export function isValidTemplate(id: string): boolean {
  return id in templates;
}
