export type TemplateCategory =
  | 'reactions'
  | 'comparisons'
  | 'social'
  | 'questioning'
  | 'success-fail'
  | 'statements'
  | 'narrative'
  | 'meta'
  | 'characters';

export type TemplatePopularity = 'high' | 'medium' | 'low';

export interface TemplateMetadata {
  usage: string;
  category: TemplateCategory;
  keywords: string[];
  similar?: string[];
  popularity?: TemplatePopularity;
}

export const templateMetadata: Record<string, TemplateMetadata> = {
  // REACTIONS & EMOTIONS (35 templates)
  'fine': {
    usage: "Things are clearly going wrong but you're pretending everything is okay; denial in the face of disaster",
    category: 'reactions',
    keywords: ['denial', 'disaster', 'okay', 'pretending', 'burning', 'fine', 'calm'],
    similar: ['harold', 'leo'],
    popularity: 'high',
  },
  'harold': {
    usage: 'Smiling through awkwardness or discomfort; hiding the pain behind a forced smile',
    category: 'reactions',
    keywords: ['awkward', 'uncomfortable', 'hiding', 'pain', 'forced', 'smile'],
    similar: ['fine', 'ams'],
    popularity: 'high',
  },
  'feelsgood': {
    usage: 'Expressing satisfaction or contentment about something',
    category: 'reactions',
    keywords: ['happy', 'satisfied', 'content', 'good', 'pleased'],
    similar: ['success', 'soa'],
    popularity: 'medium',
  },
  'sadfrog': {
    usage: 'Expressing sadness, disappointment, or feeling bad about something',
    category: 'reactions',
    keywords: ['sad', 'disappointed', 'bad', 'depressed', 'down', 'pepe'],
    similar: ['fa', 'cryingfloor'],
    popularity: 'high',
  },
  'grumpycat': {
    usage: 'Expressing grumpy disapproval or pessimistic thoughts',
    category: 'reactions',
    keywords: ['grumpy', 'disapproval', 'pessimistic', 'negative', 'hate'],
    similar: ['yuno', 'fmr'],
    popularity: 'high',
  },
  'happening': {
    usage: 'Excitement that something is finally happening or about to happen',
    category: 'reactions',
    keywords: ['excited', 'happening', 'finally', 'anticipation'],
    similar: ['money', 'live'],
    popularity: 'medium',
  },
  'facepalm': {
    usage: 'Expressing frustration, disappointment, or disbelief at stupidity',
    category: 'reactions',
    keywords: ['frustrated', 'disappointed', 'disbelief', 'stupid', 'facepalm'],
    similar: ['bad', 'dodgson'],
    popularity: 'medium',
  },
  'regret': {
    usage: 'Immediately regretting a decision or action',
    category: 'reactions',
    keywords: ['regret', 'mistake', 'bad decision', 'immediately'],
    similar: ['blb', 'tried'],
    popularity: 'medium',
  },
  'tried': {
    usage: 'Acknowledging effort despite failure or poor results',
    category: 'reactions',
    keywords: ['tried', 'effort', 'failed', 'attempt', 'participation'],
    similar: ['regret', 'blb'],
    popularity: 'medium',
  },
  'soa': {
    usage: 'Seal of approval; expressing satisfaction or acceptance',
    category: 'reactions',
    keywords: ['approval', 'satisfied', 'good', 'accept', 'pleased'],
    similar: ['feelsgood', 'success'],
    popularity: 'low',
  },
  'astronaut': {
    usage: 'Shocking revelation that something was always true; "always has been"',
    category: 'reactions',
    keywords: ['revelation', 'always', 'shocked', 'discovery', 'truth'],
    similar: ['scc', 'keanu'],
    popularity: 'high',
  },
  'scc': {
    usage: 'Having a sudden realization or epiphany; moment of clarity',
    category: 'reactions',
    keywords: ['realization', 'epiphany', 'clarity', 'sudden', 'understand'],
    similar: ['astronaut', 'keanu'],
    popularity: 'medium',
  },
  'whatyear': {
    usage: 'Being so disoriented or out of touch that you don\'t know what time period it is',
    category: 'reactions',
    keywords: ['disoriented', 'confused', 'time', 'lost', 'year'],
    similar: ['gandalf', 'fry'],
    popularity: 'low',
  },
  'gandalf': {
    usage: 'Total confusion or having no memory of something',
    category: 'reactions',
    keywords: ['confused', 'memory', 'lost', 'forgotten', 'blank'],
    similar: ['whatyear', 'noidea'],
    popularity: 'medium',
  },
  'chosen': {
    usage: 'Expressing betrayal or disappointment in someone who was supposed to be special',
    category: 'reactions',
    keywords: ['betrayal', 'disappointed', 'chosen', 'special', 'failed'],
    similar: ['regret', 'worst'],
    popularity: 'low',
  },
  'cryingfloor': {
    usage: 'Being so upset or disappointed that you\'re crying on the floor',
    category: 'reactions',
    keywords: ['crying', 'upset', 'sad', 'floor', 'devastated'],
    similar: ['sadfrog', 'fa'],
    popularity: 'low',
  },
  'worst': {
    usage: 'Correcting someone that this isn\'t the worst yet; "worst day of your life so far"',
    category: 'reactions',
    keywords: ['worst', 'yet', 'still', 'worse', 'coming'],
    similar: ['chosen', 'badchoice'],
    popularity: 'medium',
  },
  'badchoice': {
    usage: 'Realizing something was a bad choice or mistake',
    category: 'reactions',
    keywords: ['bad', 'choice', 'mistake', 'regret', 'wrong'],
    similar: ['regret', 'worst'],
    popularity: 'low',
  },
  'disastergirl': {
    usage: 'Looking pleased or satisfied while something bad is happening; scheming satisfaction',
    category: 'reactions',
    keywords: ['satisfied', 'evil', 'scheming', 'disaster', 'planned'],
    similar: ['fine', 'harold'],
    popularity: 'medium',
  },
  'ams': {
    usage: 'That awkward moment when something embarrassing happens',
    category: 'reactions',
    keywords: ['awkward', 'embarrassing', 'moment', 'uncomfortable'],
    similar: ['harold', 'awkward'],
    popularity: 'medium',
  },
  'cheems': {
    usage: 'Being nervous or anxious about something; doge variant',
    category: 'reactions',
    keywords: ['nervous', 'anxious', 'worried', 'doge', 'cheems'],
    similar: ['doge', 'afraid'],
    popularity: 'medium',
  },
  'crow': {
    usage: 'Demanding better material or quality; expressing dissatisfaction',
    category: 'reactions',
    keywords: ['dissatisfied', 'better', 'quality', 'material', 'crow'],
    similar: ['grumpycat', 'cbg'],
    popularity: 'low',
  },
  'kombucha': {
    usage: 'Trying something and having mixed feelings; initial disgust then reconsideration',
    category: 'reactions',
    keywords: ['trying', 'mixed', 'feelings', 'reconsider', 'taste'],
    similar: ['db', 'dbg'],
    popularity: 'medium',
  },
  'll': {
    usage: 'Quiet, creepy laughter; "hhhehehe"',
    category: 'reactions',
    keywords: ['laughing', 'creepy', 'giggle', 'lizard', 'hehe'],
    similar: ['disastergirl', 'rollsafe'],
    popularity: 'low',
  },
  'money': {
    usage: 'Wanting to buy something immediately; "shut up and take my money"',
    category: 'reactions',
    keywords: ['buy', 'money', 'want', 'shut up', 'take'],
    similar: ['happening', 'sohappy'],
    popularity: 'medium',
  },
  'sohappy': {
    usage: 'Would be so happy if something happened',
    category: 'reactions',
    keywords: ['happy', 'would', 'pleased', 'joy'],
    similar: ['money', 'feelsgood'],
    popularity: 'low',
  },
  'sohot': {
    usage: 'Something is very popular or trendy right now',
    category: 'reactions',
    keywords: ['popular', 'trendy', 'hot', 'now', 'zoolander'],
    similar: ['stonks', 'mb'],
    popularity: 'medium',
  },
  'seagull': {
    usage: 'Building up intensity or volume; inhaling before shouting',
    category: 'reactions',
    keywords: ['intense', 'building', 'shouting', 'loud', 'inhaling'],
    similar: ['sparta', 'live'],
    popularity: 'low',
  },
  'sf': {
    usage: 'Knowing your fate is sealed after doing something wrong',
    category: 'reactions',
    keywords: ['fate', 'sealed', 'doomed', 'caught', 'trouble'],
    similar: ['blb', 'regret'],
    popularity: 'low',
  },
  'stop-it': {
    usage: 'Telling someone to stop what they\'re doing and get help',
    category: 'reactions',
    keywords: ['stop', 'help', 'intervention', 'enough'],
    similar: ['fetch', 'imsorry'],
    popularity: 'low',
  },
  'ermg': {
    usage: 'Excited reaction in exaggerated speech; "ermahgerd"',
    category: 'reactions',
    keywords: ['excited', 'ermahgerd', 'exaggerated', 'enthusiasm'],
    similar: ['happening', 'money'],
    popularity: 'low',
  },
  'firsttry': {
    usage: 'Successfully doing something on the first attempt',
    category: 'reactions',
    keywords: ['success', 'first', 'try', 'nailed', 'achieved'],
    similar: ['success', 'soa'],
    popularity: 'low',
  },
  'gone': {
    usage: 'Something disappearing or being lost immediately; "and it\'s gone"',
    category: 'reactions',
    keywords: ['gone', 'lost', 'disappeared', 'immediately'],
    similar: ['regret', 'badchoice'],
    popularity: 'medium',
  },
  'live': {
    usage: 'Demanding to do something without preparation; "do it live"',
    category: 'reactions',
    keywords: ['live', 'now', 'unprepared', 'immediate', 'no rehearsal'],
    similar: ['sparta', 'happening'],
    popularity: 'low',
  },
  'nice': {
    usage: 'Having a small consolation despite failure; "so I got that goin\' for me, which is nice"',
    category: 'reactions',
    keywords: ['consolation', 'silver lining', 'small win', 'nice'],
    similar: ['tried', 'success'],
    popularity: 'medium',
  },

  // COMPARISONS & CHOICES (28 templates)
  'drake': {
    usage: 'Rejecting one option in favor of another; showing preference between two choices',
    category: 'comparisons',
    keywords: ['preference', 'choice', 'reject', 'approve', 'better', 'worse'],
    similar: ['pooh', 'glasses'],
    popularity: 'high',
  },
  'db': {
    usage: 'Being distracted or tempted by something new while ignoring the current thing',
    category: 'comparisons',
    keywords: ['distracted', 'tempted', 'cheating', 'ignoring', 'new'],
    similar: ['dg', 'exit'],
    popularity: 'high',
  },
  'dg': {
    usage: 'Distracted girlfriend variant; being tempted while in a relationship',
    category: 'comparisons',
    keywords: ['distracted', 'girlfriend', 'tempted', 'ignoring'],
    similar: ['db', 'exit'],
    popularity: 'medium',
  },
  'pooh': {
    usage: 'Comparing mundane vs fancy versions of the same thing; tuxedo Winnie',
    category: 'comparisons',
    keywords: ['fancy', 'mundane', 'comparison', 'sophisticated', 'tuxedo'],
    similar: ['drake', 'glasses'],
    popularity: 'high',
  },
  'glasses': {
    usage: 'Seeing something differently with and without glasses; Peter Parker',
    category: 'comparisons',
    keywords: ['vision', 'clarity', 'see', 'different', 'glasses'],
    similar: ['drake', 'pooh'],
    popularity: 'medium',
  },
  'both': {
    usage: 'Why not both? Accepting both options instead of choosing',
    category: 'comparisons',
    keywords: ['both', 'why not', 'accept', 'all', 'por que no'],
    similar: ['ds', 'handshake'],
    popularity: 'medium',
  },
  'dbg': {
    usage: 'Expectation vs reality; what you expect vs what you get',
    category: 'comparisons',
    keywords: ['expectation', 'reality', 'vs', 'different', 'disappointed'],
    similar: ['kombucha', 'worst'],
    popularity: 'medium',
  },
  'same': {
    usage: 'Two things that are actually the same despite appearing different',
    category: 'comparisons',
    keywords: ['same', 'identical', 'no difference', 'equal'],
    similar: ['spiderman', 'corporate'],
    popularity: 'high',
  },
  'spiderman': {
    usage: 'Two identical things pointing at each other; mutual accusation',
    category: 'comparisons',
    keywords: ['identical', 'pointing', 'same', 'accusation', 'mirror'],
    similar: ['same', 'corporate'],
    popularity: 'high',
  },
  'exit': {
    usage: 'Taking an unexpected exit or different path instead of continuing',
    category: 'comparisons',
    keywords: ['exit', 'different path', 'choice', 'turn', 'unexpected'],
    similar: ['db', 'dg'],
    popularity: 'medium',
  },
  'vince': {
    usage: 'Escalating excitement through multiple stages; Vince McMahon reaction',
    category: 'comparisons',
    keywords: ['escalating', 'excitement', 'stages', 'progression', 'increasingly'],
    similar: ['gb', 'perfection'],
    popularity: 'medium',
  },
  'ds': {
    usage: 'Struggling to choose between two difficult options; daily struggle',
    category: 'comparisons',
    keywords: ['struggle', 'choice', 'difficult', 'decision', 'button'],
    similar: ['both', 'drake'],
    popularity: 'medium',
  },
  'balloon': {
    usage: 'Running away from opportunities or responsibilities toward something else',
    category: 'comparisons',
    keywords: ['running', 'away', 'avoiding', 'chase', 'opportunities'],
    similar: ['db', 'exit'],
    popularity: 'low',
  },
  'handshake': {
    usage: 'Two different groups or sides agreeing on something; epic handshake',
    category: 'comparisons',
    keywords: ['agreement', 'handshake', 'common ground', 'unity', 'sides'],
    similar: ['both', 'friends'],
    popularity: 'medium',
  },
  'friends': {
    usage: 'Are you two friends? Finding unexpected common ground',
    category: 'comparisons',
    keywords: ['friends', 'common', 'unexpected', 'agreement', 'unite'],
    similar: ['handshake', 'both'],
    popularity: 'low',
  },
  'home': {
    usage: 'We have X at home; the home version is inferior',
    category: 'comparisons',
    keywords: ['home', 'inferior', 'cheap', 'knockoff', 'budget'],
    similar: ['dbg', 'same'],
    popularity: 'medium',
  },
  'midwit': {
    usage: 'Simple people and smart people agree; middle intelligence overthinks',
    category: 'comparisons',
    keywords: ['overthinking', 'simple', 'smart', 'intelligence', 'bell curve'],
    similar: ['gb', 'philosoraptor'],
    popularity: 'medium',
  },
  'oprah': {
    usage: 'Everyone gets something; Oprah giving away cars',
    category: 'comparisons',
    keywords: ['everyone', 'gets', 'giving', 'all', 'you get'],
    similar: ['both', 'xy'],
    popularity: 'medium',
  },
  'persian': {
    usage: 'Waking up disoriented or confused; Persian cat room guardian',
    category: 'comparisons',
    keywords: ['waking', 'disoriented', 'confused', 'cat', 'morning'],
    similar: ['whatyear', 'gandalf'],
    popularity: 'low',
  },
  'buzz': {
    usage: 'X, X everywhere; seeing something everywhere',
    category: 'comparisons',
    keywords: ['everywhere', 'all over', 'abundant', 'woody', 'buzz'],
    similar: ['oprah', 'xy'],
    popularity: 'medium',
  },
  'mini-keanu': {
    usage: 'Patiently waiting for something; mini Keanu waiting for mom',
    category: 'comparisons',
    keywords: ['waiting', 'patient', 'anticipation', 'kid', 'keanu'],
    similar: ['happening', 'sohappy'],
    popularity: 'low',
  },
  'slap': {
    usage: 'Someone/something interrupting or ruining a good time; Will Smith slap',
    category: 'comparisons',
    keywords: ['interrupt', 'ruin', 'slap', 'stop', 'disruption'],
    similar: ['stop', 'fetch'],
    popularity: 'medium',
  },
  'khaby-lame': {
    usage: 'Simple solution vs overcomplicated approach; Khaby Lame shrug',
    category: 'comparisons',
    keywords: ['simple', 'overcomplicated', 'obvious', 'easy', 'shrug'],
    similar: ['midwit', 'noidea'],
    popularity: 'medium',
  },
  'leo': {
    usage: 'Walking confidently despite having no idea what you\'re doing; Leo strutting',
    category: 'comparisons',
    keywords: ['confident', 'clueless', 'fake it', 'strutting', 'leo'],
    similar: ['noidea', 'rollsafe'],
    popularity: 'medium',
  },
  'saltbae': {
    usage: 'Adding finishing touches with flair; Salt Bae sprinkling',
    category: 'comparisons',
    keywords: ['finishing', 'flair', 'style', 'adding', 'salt'],
    similar: ['bender', 'genie'],
    popularity: 'low',
  },
  'stonks': {
    usage: 'Intentionally bad decisions or logic presented as good; ironic success',
    category: 'comparisons',
    keywords: ['stonks', 'bad logic', 'ironic', 'stocks', 'economics'],
    similar: ['rollsafe', 'sohot'],
    popularity: 'high',
  },
  'woman-cat': {
    usage: 'Someone yelling at someone else who is confused or defensive',
    category: 'comparisons',
    keywords: ['yelling', 'confused', 'argument', 'defensive', 'cat'],
    similar: ['chair', 'red'],
    popularity: 'high',
  },
  'ugandanknuck': {
    usage: 'Do you know the way? Ugandan Knuckles meme',
    category: 'comparisons',
    keywords: ['way', 'path', 'ugandan', 'knuckles', 'know'],
    similar: ['away', 'light'],
    popularity: 'low',
  },

  // SOCIAL SITUATIONS (24 templates)
  'awkward': {
    usage: 'Socially awkward penguin; uncomfortable social situations',
    category: 'social',
    keywords: ['awkward', 'social', 'uncomfortable', 'penguin', 'anxiety'],
    similar: ['ams', 'awesome-awkward'],
    popularity: 'medium',
  },
  'awesome': {
    usage: 'Socially awesome penguin; social wins or successful interactions',
    category: 'social',
    keywords: ['awesome', 'social', 'win', 'success', 'penguin'],
    similar: ['ggg', 'awkward-awesome'],
    popularity: 'medium',
  },
  'awesome-awkward': {
    usage: 'Starting awesome socially then becoming awkward',
    category: 'social',
    keywords: ['awesome then awkward', 'social', 'fail', 'penguin'],
    similar: ['awkward', 'awkward-awesome'],
    popularity: 'medium',
  },
  'awkward-awesome': {
    usage: 'Starting awkward socially then turning awesome',
    category: 'social',
    keywords: ['awkward then awesome', 'social', 'recovery', 'penguin'],
    similar: ['awkward', 'awesome-awkward'],
    popularity: 'medium',
  },
  'ggg': {
    usage: 'Good Guy Greg; being a genuinely good person',
    category: 'social',
    keywords: ['good guy', 'helpful', 'kind', 'generous', 'friend'],
    similar: ['awesome', 'cb'],
    popularity: 'medium',
  },
  'ss': {
    usage: 'Scumbag Steve; being a jerk or inconsiderate person',
    category: 'social',
    keywords: ['scumbag', 'jerk', 'rude', 'inconsiderate', 'bad friend'],
    similar: ['oag', 'dsm'],
    popularity: 'medium',
  },
  'oag': {
    usage: 'Overly attached girlfriend; being creepily attached or possessive',
    category: 'social',
    keywords: ['attached', 'possessive', 'creepy', 'stalker', 'girlfriend'],
    similar: ['dsm', 'ss'],
    popularity: 'medium',
  },
  'dsm': {
    usage: 'Dating site murderer; creepy or sinister comments disguised as normal',
    category: 'social',
    keywords: ['creepy', 'murderer', 'sinister', 'dating', 'dark'],
    similar: ['oag', 'ss'],
    popularity: 'low',
  },
  'afraid': {
    usage: 'Too afraid to ask at this point; missing context but afraid to admit it',
    category: 'social',
    keywords: ['afraid', 'ask', 'confused', 'missing context', 'andy'],
    similar: ['noidea', 'gandalf'],
    popularity: 'high',
  },
  'atis': {
    usage: 'And then I said... setting up a punchline or joke',
    category: 'social',
    keywords: ['and then', 'joke', 'story', 'laughing', 'telling'],
    similar: ['ch', 'wonka'],
    popularity: 'low',
  },
  'ch': {
    usage: 'Captain Hindsight; obvious advice after the fact',
    category: 'social',
    keywords: ['hindsight', 'obvious', 'advice', 'after', 'should have'],
    similar: ['atis', 'dwight'],
    popularity: 'low',
  },
  'hipster': {
    usage: 'Hipster barista being pretentious or condescending',
    category: 'social',
    keywords: ['hipster', 'pretentious', 'condescending', 'coffee', 'barista'],
    similar: ['wonka', 'cbg'],
    popularity: 'low',
  },
  'lrv': {
    usage: 'Laundry room Viking; misplaced intensity or enthusiasm',
    category: 'social',
    keywords: ['intense', 'misplaced', 'enthusiasm', 'viking', 'laundry'],
    similar: ['iw', 'sparta'],
    popularity: 'low',
  },
  'sarcasticbear': {
    usage: 'Sarcastic response; "I\'m so sorry I haven\'t memorized the internet"',
    category: 'social',
    keywords: ['sarcastic', 'annoyed', 'sorry', 'internet', 'bear'],
    similar: ['wonka', 'grumpycat'],
    popularity: 'low',
  },
  'sb': {
    usage: 'Scumbag brain; your brain working against you',
    category: 'social',
    keywords: ['brain', 'sabotage', 'memory', 'forgets', 'remembers wrong'],
    similar: ['mmm', 'blb'],
    popularity: 'medium',
  },
  'bd': {
    usage: 'Butthurt dweller; bitter neckbeard excuses',
    category: 'social',
    keywords: ['butthurt', 'neckbeard', 'excuses', 'bitter', 'dweller'],
    similar: ['ss', 'fbf'],
    popularity: 'low',
  },
  'fbf': {
    usage: 'Foul bachelor frog; gross or lazy bachelor behavior',
    category: 'social',
    keywords: ['gross', 'lazy', 'bachelor', 'frog', 'disgusting'],
    similar: ['bd', 'ss'],
    popularity: 'medium',
  },
  'kk': {
    usage: 'Karate Kyle; nerdy kid getting revenge',
    category: 'social',
    keywords: ['revenge', 'nerdy', 'dark', 'karate', 'kyle'],
    similar: ['dsm', 'iw'],
    popularity: 'low',
  },
  'mmm': {
    usage: 'Minor Mistake Marvin; small everyday mistakes',
    category: 'social',
    keywords: ['mistake', 'minor', 'everyday', 'oops', 'marvin'],
    similar: ['blb', 'sb'],
    popularity: 'low',
  },
  'puffin': {
    usage: 'Unpopular opinion puffin; stating unpopular opinions',
    category: 'social',
    keywords: ['unpopular', 'opinion', 'controversial', 'puffin'],
    similar: ['cmm', 'confession'],
    popularity: 'low',
  },
  'cb': {
    usage: 'Confession bear; confessing something',
    category: 'social',
    keywords: ['confession', 'admit', 'secret', 'bear'],
    similar: ['puffin', 'ggg'],
    popularity: 'medium',
  },
  'drunk': {
    usage: 'Drunk baby; appearing drunk or making drunk-like statements',
    category: 'social',
    keywords: ['drunk', 'baby', 'intoxicated', 'confused'],
    similar: ['tenguy', 'fbf'],
    popularity: 'low',
  },
  'tenguy': {
    usage: '10 Guy; saying something stupid while high',
    category: 'social',
    keywords: ['high', 'stupid', 'stoned', 'confused', 'guy'],
    similar: ['drunk', 'philosoraptor'],
    popularity: 'medium',
  },
  'fa': {
    usage: 'Forever alone; being lonely or socially isolated',
    category: 'social',
    keywords: ['lonely', 'alone', 'isolated', 'sad', 'forever'],
    similar: ['sadfrog', 'awkward'],
    popularity: 'medium',
  },

  // QUESTIONING & UNCERTAINTY (18 templates)
  'fry': {
    usage: 'Not sure if X or Y; expressing uncertainty between two possibilities',
    category: 'questioning',
    keywords: ['not sure', 'uncertain', 'or', 'doubt', 'squinting'],
    similar: ['keanu', 'philosoraptor'],
    popularity: 'high',
  },
  'keanu': {
    usage: 'Conspiracy Keanu; wild conspiracy theories or philosophical questions',
    category: 'questioning',
    keywords: ['conspiracy', 'what if', 'theory', 'question', 'keanu'],
    similar: ['fry', 'philosoraptor'],
    popularity: 'medium',
  },
  'philosoraptor': {
    usage: 'Philosophical questions or thought experiments',
    category: 'questioning',
    keywords: ['philosophy', 'question', 'think', 'deep', 'raptor'],
    similar: ['keanu', 'fry'],
    popularity: 'medium',
  },
  'noidea': {
    usage: 'I have no idea what I\'m doing; being completely clueless',
    category: 'questioning',
    keywords: ['clueless', 'no idea', 'lost', 'confused', 'dog'],
    similar: ['leo', 'afraid'],
    popularity: 'high',
  },
  'sk': {
    usage: 'Skeptical third world kid; questioning first world problems',
    category: 'questioning',
    keywords: ['skeptical', 'questioning', 'third world', 'doubt', 'kid'],
    similar: ['fry', 'wonka'],
    popularity: 'low',
  },
  'wonka': {
    usage: 'Condescending Wonka; sarcastic questioning of claims',
    category: 'questioning',
    keywords: ['condescending', 'sarcastic', 'really', 'tell me more', 'wonka'],
    similar: ['sk', 'hipster'],
    popularity: 'high',
  },
  'snek': {
    usage: 'Skeptical snake; side-eye skepticism',
    category: 'questioning',
    keywords: ['skeptical', 'suspicious', 'doubt', 'snake', 'side eye'],
    similar: ['fry', 'sk'],
    popularity: 'low',
  },
  'pigeon': {
    usage: 'Completely misidentifying something obvious; "is this X?"',
    category: 'questioning',
    keywords: ['misidentify', 'confused', 'wrong', 'is this', 'butterfly'],
    similar: ['noidea', 'afraid'],
    popularity: 'high',
  },
  'rollsafe': {
    usage: 'Flawed logic presented confidently; Roll Safe thinking',
    category: 'questioning',
    keywords: ['flawed logic', 'confident', 'wrong', 'thinking', 'smart'],
    similar: ['stonks', 'philosoraptor'],
    popularity: 'medium',
  },
  'inigo': {
    usage: 'You keep using that word... I don\'t think it means what you think',
    category: 'questioning',
    keywords: ['wrong word', 'misuse', 'definition', 'inigo', 'montoya'],
    similar: ['pigeon', 'wonka'],
    popularity: 'medium',
  },
  'touch': {
    usage: 'Am I out of touch? No, it\'s the children who are wrong',
    category: 'questioning',
    keywords: ['out of touch', 'wrong', 'children', 'skinner', 'blame'],
    similar: ['wonka', 'sk'],
    popularity: 'medium',
  },
  'box': {
    usage: 'What\'s in the box?! Intense questioning or curiosity',
    category: 'questioning',
    keywords: ['whats in', 'box', 'question', 'intense', 'seven'],
    similar: ['happening', 'sparta'],
    popularity: 'low',
  },
  'crazypills': {
    usage: 'Feeling like you\'re the only sane one; taking crazy pills',
    category: 'questioning',
    keywords: ['crazy', 'pills', 'sane', 'only one', 'zoolander'],
    similar: ['touch', 'fry'],
    popularity: 'low',
  },
  'waygd': {
    usage: 'What are you gonna do? Resignation to fate',
    category: 'questioning',
    keywords: ['what are you', 'gonna do', 'resignation', 'fate', 'accept'],
    similar: ['nice', 'fine'],
    popularity: 'low',
  },
  'toohigh': {
    usage: 'Something is too damn high; expressing outrage at excess',
    category: 'questioning',
    keywords: ['too high', 'damn', 'expensive', 'much', 'rent'],
    similar: ['grumpycat', 'fmr'],
    popularity: 'medium',
  },
  'yuno': {
    usage: 'Y U NO do something? Frustrated questioning',
    category: 'questioning',
    keywords: ['why', 'y u no', 'frustrated', 'question', 'rage'],
    similar: ['grumpycat', 'toohigh'],
    popularity: 'medium',
  },
  'joker': {
    usage: 'It\'s simple, [do extreme thing]; Joker\'s plan',
    category: 'questioning',
    keywords: ['simple', 'plan', 'extreme', 'joker', 'batman'],
    similar: ['gru', 'sparta'],
    popularity: 'low',
  },
  'wishes': {
    usage: 'Genie rules; wishing for something only to have rules prevent it',
    category: 'questioning',
    keywords: ['genie', 'rules', 'wish', 'prevented', 'cant'],
    similar: ['genie', 'bender'],
    popularity: 'low',
  },

  // SUCCESS & FAILURE (16 templates)
  'success': {
    usage: 'Success kid; achieving small victories or wins',
    category: 'success-fail',
    keywords: ['success', 'win', 'victory', 'achievement', 'yes'],
    similar: ['awesome', 'firsttry'],
    popularity: 'high',
  },
  'blb': {
    usage: 'Bad Luck Brian; everything going wrong through no fault of your own',
    category: 'success-fail',
    keywords: ['bad luck', 'failure', 'wrong', 'unlucky', 'brian'],
    similar: ['mmm', 'tried'],
    popularity: 'high',
  },
  'mw': {
    usage: 'I guarantee it; confidently guaranteeing something',
    category: 'success-fail',
    keywords: ['guarantee', 'confident', 'sure', 'promise', 'menswearhouse'],
    similar: ['dwight', 'interesting'],
    popularity: 'low',
  },
  'biw': {
    usage: 'Baby insanity wolf; mildly rebellious or daring actions',
    category: 'success-fail',
    keywords: ['rebellious', 'daring', 'mild', 'baby', 'wolf'],
    similar: ['iw', 'awesome'],
    popularity: 'low',
  },
  'iw': {
    usage: 'Insanity wolf; extremely reckless or insane actions',
    category: 'success-fail',
    keywords: ['insane', 'reckless', 'extreme', 'wolf', 'crazy'],
    similar: ['biw', 'sparta'],
    popularity: 'medium',
  },
  'bihw': {
    usage: 'It ain\'t much but it\'s honest work',
    category: 'success-fail',
    keywords: ['honest', 'work', 'aint much', 'humble', 'simple'],
    similar: ['success', 'tried'],
    popularity: 'medium',
  },
  'boat': {
    usage: 'I should buy a boat cat; spontaneous purchasing decisions',
    category: 'success-fail',
    keywords: ['buy', 'boat', 'should', 'purchase', 'cat'],
    similar: ['money', 'happening'],
    popularity: 'low',
  },
  'icanhas': {
    usage: 'I can has cheezburger? LOLcat speak; wanting something',
    category: 'success-fail',
    keywords: ['can has', 'lolcat', 'want', 'cheezburger', 'request'],
    similar: ['doge', 'boat'],
    popularity: 'low',
  },
  'jetpack': {
    usage: 'Nothing to do here; leaving an awkward situation',
    category: 'success-fail',
    keywords: ['leaving', 'nothing', 'awkward', 'jetpack', 'exit'],
    similar: ['exit', 'away'],
    popularity: 'low',
  },
  'aag': {
    usage: 'Ancient aliens guy; attributing everything to aliens',
    category: 'success-fail',
    keywords: ['aliens', 'therefore', 'ancient', 'history channel'],
    similar: ['keanu', 'away'],
    popularity: 'medium',
  },
  'away': {
    usage: 'Life finds a way; things working out despite obstacles',
    category: 'success-fail',
    keywords: ['life', 'finds', 'way', 'overcome', 'jurassic'],
    similar: ['aag', 'success'],
    popularity: 'low',
  },
  'center': {
    usage: 'What is this, a center for ants?! Things being too small',
    category: 'success-fail',
    keywords: ['too small', 'ants', 'tiny', 'zoolander', 'what is this'],
    similar: ['toohigh', 'crazypills'],
    popularity: 'low',
  },
  'country': {
    usage: 'What a country! Expressing absurdity about a situation',
    category: 'success-fail',
    keywords: ['country', 'absurd', 'strange', 'yakov'],
    similar: ['touch', 'crazypills'],
    popularity: 'low',
  },
  'bender': {
    usage: 'I\'m going to build my own X with blackjack and hookers',
    category: 'success-fail',
    keywords: ['build', 'own', 'blackjack', 'hookers', 'bender'],
    similar: ['sparta', 'money'],
    popularity: 'medium',
  },
  'genie': {
    usage: 'Phenomenal cosmic power, itty bitty living space',
    category: 'success-fail',
    keywords: ['power', 'space', 'tradeoff', 'genie', 'aladdin'],
    similar: ['wishes', 'fwp'],
    popularity: 'low',
  },

  // STATEMENTS & OPINIONS (15 templates)
  'cmm': {
    usage: 'Change my mind; stating a controversial opinion or hot take',
    category: 'statements',
    keywords: ['opinion', 'hot take', 'change', 'mind', 'crowder'],
    similar: ['puffin', 'dwight'],
    popularity: 'high',
  },
  'sparta': {
    usage: 'This is Sparta! Emphatic declaration or rejection',
    category: 'statements',
    keywords: ['sparta', 'this is', 'emphatic', 'declaration', 'kick'],
    similar: ['iw', 'mordor'],
    popularity: 'medium',
  },
  'mordor': {
    usage: 'One does not simply walk into Mordor; stating difficulty of task',
    category: 'statements',
    keywords: ['does not simply', 'difficult', 'impossible', 'boromir', 'mordor'],
    similar: ['sparta', 'inigo'],
    popularity: 'high',
  },
  'morpheus': {
    usage: 'What if I told you... revealing surprising truth',
    category: 'statements',
    keywords: ['what if', 'told you', 'truth', 'reveal', 'matrix'],
    similar: ['astronaut', 'morpheus'],
    popularity: 'high',
  },
  'dwight': {
    usage: 'Schrute facts; correcting with "False" then stating fact',
    category: 'statements',
    keywords: ['false', 'actually', 'correction', 'fact', 'schrute'],
    similar: ['mw', 'ch'],
    popularity: 'medium',
  },
  'ackbar': {
    usage: 'It\'s a trap! Warning that something is a trap',
    category: 'statements',
    keywords: ['trap', 'warning', 'ackbar', 'star wars'],
    similar: ['astronaut', 'sparta'],
    popularity: 'medium',
  },
  'bad': {
    usage: 'Your X is bad and you should feel bad',
    category: 'statements',
    keywords: ['bad', 'feel bad', 'criticism', 'zoidberg'],
    similar: ['grumpycat', 'cbg'],
    popularity: 'medium',
  },
  'cake': {
    usage: 'I was told there would be cake; disappointed expectations',
    category: 'statements',
    keywords: ['told', 'cake', 'disappointed', 'milton', 'office space'],
    similar: ['dbg', 'blb'],
    popularity: 'low',
  },
  'captain': {
    usage: 'Look at me, I am the captain now',
    category: 'statements',
    keywords: ['captain', 'now', 'takeover', 'control', 'look at me'],
    similar: ['sparta', 'bender'],
    popularity: 'medium',
  },
  'fetch': {
    usage: 'Stop trying to make fetch happen, it\'s not going to happen',
    category: 'statements',
    keywords: ['stop', 'not happening', 'fetch', 'mean girls'],
    similar: ['bad', 'dodgson'],
    popularity: 'medium',
  },
  'imsorry': {
    usage: 'Oh I\'m sorry, I thought this was America',
    category: 'statements',
    keywords: ['sorry', 'america', 'freedom', 'randy', 'south park'],
    similar: ['sparta', 'red'],
    popularity: 'low',
  },
  'fmr': {
    usage: 'Fuck me, right? Sarcastically accepting blame',
    category: 'statements',
    keywords: ['fuck me', 'right', 'sarcastic', 'blame', 'superbad'],
    similar: ['grumpycat', 'yuno'],
    popularity: 'medium',
  },
  'elf': {
    usage: 'You sit on a throne of lies; accusing of dishonesty',
    category: 'statements',
    keywords: ['lies', 'throne', 'dishonest', 'elf', 'santa'],
    similar: ['bad', 'grumpycat'],
    popularity: 'low',
  },
  'soup-nazi': {
    usage: 'No soup for you! Denying someone something',
    category: 'statements',
    keywords: ['no soup', 'denied', 'rejection', 'seinfeld', 'nazi'],
    similar: ['sparta', 'ackbar'],
    popularity: 'low',
  },
  'headaches': {
    usage: 'Types of headaches; categorizing levels of annoyance',
    category: 'statements',
    keywords: ['headache', 'types', 'annoying', 'levels'],
    similar: ['ds', 'gb'],
    popularity: 'low',
  },

  // NARRATIVE & DIALOGUE (22 templates)
  'gru': {
    usage: 'Gru\'s plan; a plan that goes wrong in the final step',
    category: 'narrative',
    keywords: ['plan', 'backfire', 'wrong', 'steps', 'gru'],
    similar: ['reveal', 'perfection'],
    popularity: 'high',
  },
  'chair': {
    usage: 'American Chopper argument; escalating argument between two people',
    category: 'narrative',
    keywords: ['argument', 'escalating', 'fight', 'debate', 'chopper'],
    similar: ['woman-cat', 'red'],
    popularity: 'medium',
  },
  'perfection': {
    usage: 'Three-stage preference; rejecting first two, accepting third',
    category: 'narrative',
    keywords: ['perfection', 'three', 'stages', 'preference', 'chef kiss'],
    similar: ['gru', 'vince'],
    popularity: 'medium',
  },
  'reveal': {
    usage: 'Scooby Doo reveal; unmasking to show true identity',
    category: 'narrative',
    keywords: ['reveal', 'unmask', 'identity', 'scooby', 'villain'],
    similar: ['gru', 'astronaut'],
    popularity: 'medium',
  },
  'gb': {
    usage: 'Galaxy brain; increasingly absurd or enlightened takes',
    category: 'narrative',
    keywords: ['galaxy', 'brain', 'expanding', 'absurd', 'enlightened'],
    similar: ['vince', 'midwit'],
    popularity: 'high',
  },
  'panik-kalm-panik': {
    usage: 'Emotional rollercoaster; panic, calm, then panic again',
    category: 'narrative',
    keywords: ['panik', 'kalm', 'panic', 'rollercoaster', 'anxiety'],
    similar: ['gru', 'worst'],
    popularity: 'medium',
  },
  'stop': {
    usage: 'Stop it Patrick, you\'re scaring him; multi-line dialogue',
    category: 'narrative',
    keywords: ['stop', 'scaring', 'patrick', 'spongebob', 'dialogue'],
    similar: ['wallet', 'ptj'],
    popularity: 'low',
  },
  'wallet': {
    usage: 'Patrick\'s wallet; absurd logic conversation',
    category: 'narrative',
    keywords: ['wallet', 'patrick', 'logic', 'absurd', 'conversation'],
    similar: ['stop', 'ptj'],
    popularity: 'low',
  },
  'ptj': {
    usage: 'Phoebe teaching Joey; repeating dialogue',
    category: 'narrative',
    keywords: ['teaching', 'repeat', 'phoebe', 'joey', 'friends'],
    similar: ['wallet', 'stop'],
    popularity: 'low',
  },
  'captain-america': {
    usage: 'Captain America elevator dad joke setup',
    category: 'narrative',
    keywords: ['dad joke', 'setup', 'punchline', 'elevator', 'captain america'],
    similar: ['atis', 'say'],
    popularity: 'low',
  },
  'say': {
    usage: 'Say the line, Bart! Predictable response',
    category: 'narrative',
    keywords: ['say', 'line', 'predictable', 'bart', 'simpsons'],
    similar: ['remembers', 'older'],
    popularity: 'medium',
  },
  'red': {
    usage: 'Oh is that what we\'re going to do today? We\'re going to fight?',
    category: 'narrative',
    keywords: ['fight', 'today', 'red', '70s show', 'argument'],
    similar: ['chair', 'woman-cat'],
    popularity: 'medium',
  },
  'wkh': {
    usage: 'Who killed Hannibal? Blaming others for your own actions',
    category: 'narrative',
    keywords: ['blame', 'killed', 'own fault', 'hannibal', 'eric andre'],
    similar: ['reveal', 'astronaut'],
    popularity: 'medium',
  },
  'drowning': {
    usage: 'Drowning high five; ignoring someone who needs help',
    category: 'narrative',
    keywords: ['drowning', 'ignore', 'help', 'high five', 'useless'],
    similar: ['pool', 'mouth'],
    popularity: 'low',
  },
  'grave': {
    usage: 'Grant Gustin next to grave; mourning something',
    category: 'narrative',
    keywords: ['grave', 'mourning', 'dead', 'rip', 'flash'],
    similar: ['worst', 'blb'],
    popularity: 'low',
  },
  'pool': {
    usage: 'Mother ignoring kid drowning in pool; priorities',
    category: 'narrative',
    keywords: ['ignore', 'drowning', 'priorities', 'pool', 'mother'],
    similar: ['drowning', 'mouth'],
    popularity: 'medium',
  },
  'mouth': {
    usage: 'Woman holding dog\'s mouth; preventing truth from being revealed',
    category: 'narrative',
    keywords: ['silence', 'truth', 'prevent', 'mouth', 'dog'],
    similar: ['pool', 'drowning'],
    popularity: 'low',
  },
  'nails': {
    usage: 'Guy hammering nails into sand; futile efforts',
    category: 'narrative',
    keywords: ['futile', 'pointless', 'nails', 'sand', 'useless'],
    similar: ['tried', 'blb'],
    popularity: 'low',
  },
  'ntot': {
    usage: 'No take, only throw; wanting contradictory things',
    category: 'narrative',
    keywords: ['contradiction', 'no take', 'throw', 'dog', 'want both'],
    similar: ['ds', 'both'],
    popularity: 'low',
  },
  'noah': {
    usage: 'What the hell is this? Four-panel questioning',
    category: 'narrative',
    keywords: ['what', 'hell', 'this', 'noah', 'confused'],
    similar: ['reveal', 'gru'],
    popularity: 'low',
  },
  'millers': {
    usage: 'You guys are getting paid? Discovering others have it better',
    category: 'narrative',
    keywords: ['paid', 'getting', 'surprised', 'millers', 'unfair'],
    similar: ['astronaut', 'scc'],
    popularity: 'medium',
  },
  'elmo': {
    usage: 'Elmo choosing cocaine; choosing the destructive option',
    category: 'narrative',
    keywords: ['choice', 'cocaine', 'elmo', 'destructive', 'drugs'],
    similar: ['ds', 'exit'],
    popularity: 'low',
  },

  // META & SELF-REFERENTIAL (12 templates)
  'older': {
    usage: 'It\'s an older meme sir, but it checks out',
    category: 'meta',
    keywords: ['older', 'meme', 'checks out', 'star wars', 'meta'],
    similar: ['remembers', 'made'],
    popularity: 'medium',
  },
  'made': {
    usage: 'I made this; taking credit for others\' work',
    category: 'meta',
    keywords: ['made', 'credit', 'steal', 'repost', 'comic'],
    similar: ['older', 'xy'],
    popularity: 'medium',
  },
  'xy': {
    usage: 'X all the Y! Doing something to everything',
    category: 'meta',
    keywords: ['all', 'everything', 'hyperbole', 'memes'],
    similar: ['buzz', 'oprah'],
    popularity: 'medium',
  },
  'doge': {
    usage: 'Such wow, very meme; doge speak',
    category: 'meta',
    keywords: ['doge', 'such', 'very', 'wow', 'shibe'],
    similar: ['cheems', 'icanhas'],
    popularity: 'high',
  },
  'remembers': {
    usage: 'Pepperidge Farm remembers; nostalgic memory',
    category: 'meta',
    keywords: ['remember', 'pepperidge', 'farm', 'nostalgia', 'old'],
    similar: ['older', 'say'],
    popularity: 'medium',
  },
  'jd': {
    usage: 'Joseph Ducreux; archaic language for modern concepts',
    category: 'meta',
    keywords: ['archaic', 'old english', 'ducreux', 'acquire currency'],
    similar: ['doge', 'icanhas'],
    popularity: 'low',
  },
  'yodawg': {
    usage: 'Yo dawg I heard you like X so I put X in your X',
    category: 'meta',
    keywords: ['yo dawg', 'recursive', 'xzibit', 'inception'],
    similar: ['made', 'bender'],
    popularity: 'low',
  },
  'yallgot': {
    usage: 'Y\'all got any more of them X? Desperately wanting more',
    category: 'meta',
    keywords: ['yall', 'got', 'more', 'desperate', 'dave chappelle'],
    similar: ['icanhas', 'money'],
    popularity: 'medium',
  },
  'cbg': {
    usage: 'Comic Book Guy; "worst thing ever!"',
    category: 'meta',
    keywords: ['worst', 'ever', 'comic book', 'nerd', 'simpsons'],
    similar: ['bad', 'grumpycat'],
    popularity: 'low',
  },
  'ive': {
    usage: 'Jony Ive redesigns; minimalist Apple-style redesign',
    category: 'meta',
    keywords: ['apple', 'redesign', 'jony ive', 'minimalist', 'design'],
    similar: ['sohot', 'stonks'],
    popularity: 'low',
  },
  'mb': {
    usage: 'Member berries; nostalgia for the past',
    category: 'meta',
    keywords: ['member', 'remember', 'nostalgia', 'berries', 'south park'],
    similar: ['remembers', 'older'],
    popularity: 'low',
  },
  'dodgson': {
    usage: 'See? Nobody cares',
    category: 'meta',
    keywords: ['nobody', 'cares', 'jurassic', 'dodgson', 'indifferent'],
    similar: ['facepalm', 'bad'],
    popularity: 'low',
  },

  // CHARACTERS (37 templates)
  'trump': {
    usage: 'Donald Trump claiming something is the best or biggest ever',
    category: 'characters',
    keywords: ['trump', 'best', 'biggest', 'ever', 'tremendous'],
    similar: ['mw', 'interesting'],
    popularity: 'medium',
  },
  'sad-biden': {
    usage: 'Sad Joe Biden; looking disappointed',
    category: 'characters',
    keywords: ['biden', 'sad', 'disappointed', 'joe'],
    similar: ['sad-obama', 'sadfrog'],
    popularity: 'low',
  },
  'sad-obama': {
    usage: 'Sad Barack Obama; looking disappointed',
    category: 'characters',
    keywords: ['obama', 'sad', 'disappointed', 'barack'],
    similar: ['sad-biden', 'sadfrog'],
    popularity: 'low',
  },
  'sad-bush': {
    usage: 'Sad George Bush; looking disappointed',
    category: 'characters',
    keywords: ['bush', 'sad', 'disappointed', 'george'],
    similar: ['sad-biden', 'sad-obama'],
    popularity: 'low',
  },
  'sad-clinton': {
    usage: 'Sad Bill Clinton; looking disappointed',
    category: 'characters',
    keywords: ['clinton', 'sad', 'disappointed', 'bill'],
    similar: ['sad-biden', 'sad-obama'],
    popularity: 'low',
  },
  'sad-boehner': {
    usage: 'Sad John Boehner; looking disappointed',
    category: 'characters',
    keywords: ['boehner', 'sad', 'disappointed', 'john'],
    similar: ['sad-biden', 'sad-obama'],
    popularity: 'low',
  },
  'hagrid': {
    usage: 'I should not have said that; regretting revelation',
    category: 'characters',
    keywords: ['shouldnt', 'said', 'regret', 'hagrid', 'harry potter'],
    similar: ['regret', 'sf'],
    popularity: 'medium',
  },
  'jim': {
    usage: 'Jim Halpert pointing to whiteboard',
    category: 'characters',
    keywords: ['jim', 'office', 'explaining', 'whiteboard', 'pointing'],
    similar: ['dwight', 'officespace'],
    popularity: 'medium',
  },
  'michael-scott': {
    usage: 'Michael Scott "No, God! No!" reaction',
    category: 'characters',
    keywords: ['no', 'god', 'michael', 'scott', 'office'],
    similar: ['facepalm', 'regret'],
    popularity: 'medium',
  },
  'kramer': {
    usage: 'Kramer, what\'s going on in there?',
    category: 'characters',
    keywords: ['kramer', 'seinfeld', 'happening', 'chaos'],
    similar: ['fine', 'red'],
    popularity: 'low',
  },
  'officespace': {
    usage: 'Yeah that\'d be great; passive aggressive request',
    category: 'characters',
    keywords: ['yeah', 'great', 'lumberg', 'office space', 'request'],
    similar: ['jim', 'dwight'],
    popularity: 'medium',
  },
  'interesting': {
    usage: 'I don\'t always X, but when I do Y; Most Interesting Man',
    category: 'characters',
    keywords: ['dont always', 'when i do', 'interesting', 'dos equis', 'beer'],
    similar: ['mw', 'trump'],
    popularity: 'medium',
  },
  'jw': {
    usage: 'Probably not a good idea; Jeff Goldblum warning',
    category: 'characters',
    keywords: ['probably', 'not good', 'idea', 'goldblum', 'jurassic'],
    similar: ['away', 'ackbar'],
    popularity: 'low',
  },
  'bilbo': {
    usage: 'After all, why not? Why shouldn\'t I keep it?',
    category: 'characters',
    keywords: ['why not', 'keep', 'bilbo', 'ring', 'lotr'],
    similar: ['both', 'bender'],
    popularity: 'low',
  },
  'right': {
    usage: 'Anakin and Padme; asking for reassurance, not getting it',
    category: 'characters',
    keywords: ['right', 'reassurance', 'anakin', 'padme', 'star wars'],
    similar: ['gru', 'panik-kalm-panik'],
    popularity: 'medium',
  },
  'light': {
    usage: 'Everything the light touches; territory and boundaries',
    category: 'characters',
    keywords: ['light', 'kingdom', 'territory', 'lion king', 'simba'],
    similar: ['sparta', 'mordor'],
    popularity: 'low',
  },
  'stew': {
    usage: 'Baby you\'ve got a stew going',
    category: 'characters',
    keywords: ['stew', 'going', 'arrested', 'development', 'carl weathers'],
    similar: ['bender', 'genie'],
    popularity: 'low',
  },
  'because': {
    usage: 'Just because X doesn\'t mean Y; Men in Black',
    category: 'characters',
    keywords: ['just because', 'doesnt mean', 'mib', 'stereotype'],
    similar: ['inigo', 'dwight'],
    popularity: 'low',
  },
  'bongo': {
    usage: 'Bongo cat; comparing sound volumes',
    category: 'characters',
    keywords: ['volume', 'sound', 'loud', 'quiet', 'cat'],
    similar: ['dbg', 'same'],
    popularity: 'low',
  },
  'bs': {
    usage: 'This is bull, shark; getting caught repeatedly',
    category: 'characters',
    keywords: ['bull', 'shark', 'caught', 'again', 'surprised'],
    similar: ['blb', 'sf'],
    popularity: 'low',
  },
  'bus': {
    usage: 'Two guys on a bus; before and after',
    category: 'characters',
    keywords: ['before', 'after', 'bus', 'change', 'contrast'],
    similar: ['dbg', 'glasses'],
    popularity: 'low',
  },
  'cbb': {
    usage: 'Communist Bugs Bunny; our X',
    category: 'characters',
    keywords: ['communist', 'our', 'bugs', 'bunny', 'share'],
    similar: ['oprah', 'handshake'],
    popularity: 'medium',
  },
  'dragon': {
    usage: 'What color do you want your dragon? Misunderstanding',
    category: 'characters',
    keywords: ['dragon', 'color', 'boyfriend', 'misunderstanding'],
    similar: ['pigeon', 'afraid'],
    popularity: 'low',
  },
  'fwp': {
    usage: 'First world problems; trivial complaints',
    category: 'characters',
    keywords: ['first world', 'problems', 'trivial', 'complaints', 'privileged'],
    similar: ['sk', 'toohigh'],
    popularity: 'medium',
  },
  'gears': {
    usage: 'You know what really grinds my gears?',
    category: 'characters',
    keywords: ['grinds', 'gears', 'annoying', 'peter griffin', 'family guy'],
    similar: ['grumpycat', 'yuno'],
    popularity: 'medium',
  },
  'kermit': {
    usage: 'But that\'s none of my business; sipping tea while judging',
    category: 'characters',
    keywords: ['tea', 'none', 'business', 'kermit', 'judging'],
    similar: ['wonka', 'sarcasticbear'],
    popularity: 'medium',
  },
  'patrick': {
    usage: 'Push it somewhere else Patrick; relocating the problem',
    category: 'characters',
    keywords: ['push', 'somewhere else', 'patrick', 'relocate', 'problem'],
    similar: ['rollsafe', 'philosoraptor'],
    popularity: 'low',
  },
  'spongebob': {
    usage: 'Mocking spongebob; mocking something with mixed caps',
    category: 'characters',
    keywords: ['mocking', 'mixed caps', 'spongebob', 'sarcasm'],
    similar: ['wonka', 'sarcasticbear'],
    popularity: 'high',
  },
  'ski': {
    usage: 'If you X, you\'re gonna have a bad time',
    category: 'characters',
    keywords: ['bad time', 'warning', 'ski', 'instructor', 'south park'],
    similar: ['ackbar', 'ch'],
    popularity: 'medium',
  },
  'winter': {
    usage: 'Brace yourselves, X is coming',
    category: 'characters',
    keywords: ['brace', 'coming', 'winter', 'stark', 'got'],
    similar: ['ackbar', 'ski'],
    popularity: 'medium',
  },
  'agnes': {
    usage: 'Winking after lying; agreeing to terms without reading',
    category: 'characters',
    keywords: ['wink', 'lying', 'terms', 'conditions', 'agnes'],
    similar: ['rollsafe', 'noidea'],
    popularity: 'low',
  },
  'aint-got-time': {
    usage: 'Ain\'t nobody got time fo\' that',
    category: 'characters',
    keywords: ['aint', 'nobody', 'time', 'sweet brown', 'busy'],
    similar: ['jetpack', 'exit'],
    popularity: 'medium',
  },
  'ants': {
    usage: 'Do you want ants? Because that\'s how you get ants',
    category: 'characters',
    keywords: ['ants', 'how you get', 'archer', 'consequence'],
    similar: ['ski', 'ch'],
    popularity: 'low',
  },
  'apcr': {
    usage: 'Almost politically correct redneck; good intention, bad execution',
    category: 'characters',
    keywords: ['redneck', 'almost', 'politically correct', 'awkward'],
    similar: ['awesome-awkward', 'tried'],
    popularity: 'low',
  },
  'prop3': {
    usage: 'Too confusing, too extreme; rejecting both extremes',
    category: 'characters',
    keywords: ['confusing', 'extreme', 'both', 'reject'],
    similar: ['ds', 'midwit'],
    popularity: 'low',
  },
  'spirit': {
    usage: 'Fake Spirit Halloween costume; disappointing or empty',
    category: 'characters',
    keywords: ['spirit', 'halloween', 'costume', 'nothing', 'disappointing'],
    similar: ['dbg', 'cake'],
    popularity: 'low',
  },
  'zero-wing': {
    usage: 'All your base are belong to us',
    category: 'characters',
    keywords: ['all your base', 'zero wing', 'engrish', 'old meme'],
    similar: ['older', 'jd'],
    popularity: 'low',
  },
  'wddth': {
    usage: 'We don\'t do that here; rejecting a practice or behavior',
    category: 'characters',
    keywords: ['dont do that', 'here', 'black panther', 'reject'],
    similar: ['sparta', 'mordor'],
    popularity: 'low',
  },
};
